name: Deploy to Hostinger
  
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install PHP Dependencies
        run: |
          composer install --optimize-autoloader

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Project via Rsync
        run: |
          rsync -avz --progress \
            -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa" \
            ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_DEPLOY_PATH }}
 
      - name: Run Laravel Migration
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          "cd ${{ secrets.REMOTE_DEPLOY_PATH }} && php artisan migrate --force && php artisan db:seed --force"

      - name: Create Storage Symlink
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa \
          -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
          "cd ${{ secrets.REMOTE_DEPLOY_PATH }} && php artisan storage:link"
